apiVersion: v1
kind: Secret
metadata:
  name: openai
type: Opaque
stringData:
  OPENAI_API_KEY: "dummy"
  OPENAI_BASE_URL: https://isvc-granite-31-8b-fp8-predictor.sandbox-shared-models.svc.cluster.local:8443/v1
  OPENAI_MODEL: isvc-granite-31-8b-fp8
