# Kafka configuration
camel.component.kafka.brokers=localhost:9092
camel.kafka.topic.logs=otlp_logs
camel.kafka.topic.spans=otlp_spans

# Infinispan configuration
camel.component.infinispan.hosts=localhost:11222
camel.component.infinispan.username=admin
camel.component.infinispan.password=password
# camel.component.infinispan.password={{env:INFINISPAN_KEY}} {{secret:k8s-infinispan/key}} {{hashicorp:secret:infinispan#key}} {{azure:infinispan#key}}
camel.component.infinispan.sasl-mechanism=DIGEST-MD5
camel.component.infinispan.security-realm=default
camel.component.infinispan.security-server-name=infinispan
camel.component.infinispan.secure=true

# Artemis JMS configuration
camel.beans.artemisCF = #class:org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory
camel.beans.artemisCF.brokerURL = tcp://localhost:61616
camel.beans.artemisCF.user = artemis
camel.beans.artemisCF.password = artemis
camel.beans.poolCF = #class:org.messaginghub.pooled.jms.JmsPoolConnectionFactory
camel.beans.poolCF.connectionFactory = #bean:artemisCF
camel.beans.poolCF.maxSessionsPerConnection = 500
camel.beans.poolCF.connectionIdleTimeout = 20000
camel.component.jms.connection-factory = #bean:poolCF
camel.jms.queue.error-logs=error-logs
camel.jms.queue.ai-prompts=ai-prompts
camel.jms.queue.ai-prompts-read=ai-prompts-read

# Camel configuration
camel.main.name=correlator

# Micrometer metrics
camel.metrics.enabled=true
camel.metrics.enableRoutePolicy=true
camel.metrics.enableExchangeEventNotifier=true
camel.metrics.enableRouteEventNotifier=true
camel.metrics.binders=jvm-memory,jvm-gc,processor

# Management server (Prometheus scrape endpoint)
camel.management.enabled=true
camel.management.metricsEnabled=true
camel.management.port=9090
