<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions">
    <xsl:output method="text" indent="yes"/>
    <xsl:param name="logs"/>
    <xsl:variable name="logs-x" select="json-to-xml($logs)"/>
    <xsl:variable name="mapped-xml">
        <map xmlns="http://www.w3.org/2005/xpath-functions">
            <string key="timeUnixNano">
                <xsl:value-of select="$logs-x/fn:map/fn:string[@key='timeUnixNano']"/>
            </string>
            <string key="observedTimeUnixNano">
                <xsl:value-of select="$logs-x/fn:map/fn:string[@key='observedTimeUnixNano']"/>
            </string>
            <string key="severityText">
                <xsl:value-of select="$logs-x/fn:map/fn:string[@key='severityText']"/>
            </string>
            <string key="message">
                <xsl:value-of select="$logs-x/fn:map/fn:map[@key='body']/fn:string[@key='stringValue']"/>
                <xsl:for-each select="$logs-x/fn:map/fn:array[@key='attributes']/fn:map">
                    <xsl:value-of select="concat('&#10;', fn:string[@key='key'], ': ', fn:map[@key='value']/fn:string[@key='stringValue'])"/>
                </xsl:for-each>
            </string>
            <string key="traceId">
                <xsl:value-of select="$logs-x/fn:map/fn:string[@key='traceId']"/>
            </string>
            <string key="spanId">
                <xsl:value-of select="$logs-x/fn:map/fn:string[@key='spanId']"/>
            </string>
            <string key="type">
                <xsl:value-of select="'log'"/>
            </string>
        </map>
    </xsl:variable>
    <xsl:template match="/">
        <xsl:value-of select="xml-to-json($mapped-xml)"/>
    </xsl:template>
</xsl:stylesheet>